# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Archive-Any-Create
version:      0.01
version_from: lib/Archive/Any/Create.pm
installdirs:  site
requires:
    Archive::Tar:                  0
    Archive::Zip:                  0
    Exception::Class:              0
    PerlIO::gzip:                  0
    Test::More:                    0.32
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
